### ISSUE TITLE
Add TypeScript definitions 

### ISSUE THREAD

**Issue by antonmedv** [smallhelm/ansi-style-parser#3]
Add TypeScript definitions 👨🏼‍🚀.

**Comment by farskipper** [comment]
Sure I'm not opposed to that. I'm not very up-to-date on typescript so if you or someone else could send it as a PR. The essence of it is something like this:
```
interface Result {
  styles: string[];
  text: string;
}
...
parser: (src: string) => Result[]
```

**Comment by antonmedv** [comment]
Got another problem: CRA can build project with ansi-style-parser as one deps uses es6 (instead of es5): sindre's regexp.

Copy pasted lib.
